### ISSUE TITLE
Linux port

### ISSUE THREAD

**Issue by FreeFull** [pete-gordon/hivelytracker#8]
It is possible to run HivelyTracker in Wine, but a native port would be nice to have :)

**Comment by pulkomandy** [comment]
It is possible to compile on Linux since https://github.com/pete-gordon/hivelytracker/commit/98ccbeee7677ff92db8260d97993d4177b4686a9.

GTK is used to provide the "native" parts (file requesters, etc).

Providing a generic "Linux" binary, however, is hard, because so many slightly incompatible Linux distros.

**Comment by pete-gordon** [comment]
Agree with Pulkomandy. Closing this issue.
